### ISSUE TITLE
Installed cloner build in archer c7 v5 (OpenWrt),  

### ISSUE THREAD

**Issue by nullc0rp** [xchwarze/wifi-pineapple-cloner#17]
Hello.

Sorry if I'm doing something wrong, I'm submitting this issue as last resort after searching everywhere.

I installed this build from the builds repository on my tp-link archer c7 v5:
https://github.com/xchwarze/wifi-pineapple-cloner-builds/blob/main/tetra-releases/archer-c7-v5-tetra-sysupgrade.bin

Every step seems to be working just fine (installed openwrt, ssh and then sysupgrade), but after the update the router gets in a "frozen" state. I get only the "ON" led, even if I have some ethernet ports connected and I get no Ip from eth0. Wifi is also not seen.

I had to use the Tftp process to recover to OpenWRT, and tried again with the same results. I even tried the "mini" build, same problem.

Here's the dump of the sysupgrade and first boot. I went through it, but I cant figure out what's wrong with the install.
[dumpUpgradeAndBoot.txt](https://github.com/xchwarze/wifi-pineapple-cloner/files/9553220/dumpUpgradeAndBoot.txt)

Thanks for the help, any information you may need please let me know.

**Comment by nullc0rp** [comment]
I'm starting to think I'm not connecting properly to the device. I'm on ubuntu, tried USB and ethernet and I get no dhcp. Also tried setting the address manually but I cant get to 172.16.42.1:1471, nor ping to 172.16.42.1.

**Comment by bakabaka** [comment]
> Every step seems to be working just fine (installed openwrt, ssh and when sysupgrade), but after the update the router gets in a "frozen" state. I get only the "ON" led, even if I have some ethernet ports connected and I get no Ip from eth0. Wifi is also not seen.
I experienced this as well with the ar150, had to connect via serial to up the network devices and set the wireless config files at /etc/config/wireless via "wifi config > /etc/config/wireless", this is probably due to the fact that the devices are for some reason not recognized properly out of the box. [1]

> I had to use the Tftp process to recover to OpenWRT, and tried again with the same results. I even tried the "mini" build, same problem.
See [1], its has to do with the guts of the firmware, i have a few issues open that you will have to also go through probably
when flashing fresh and after resets, sometimes you are presented with an ipv6 address (unconfirmed) but setting your ip address to 172.16.42.2, netmask to 255.255.255.0 and gateway yo 172.16.42.1 will let you access the box... probably

**Comment by xchwarze** [comment]
I just downgraded my archer C7 from openwrt 22 to [archer-c7-v5-tetra-mini-sysupgrade.bin](https://github.com/xchwarze/wifi-pineapple-cloner-builds/blob/main/tetra-releases/archer-c7-v5-tetra-mini-sysupgrade.bin) without any problems.

I connected to the router from ETH1 and did not experience any ip assignment errors

![image](https://user-images.githubusercontent.com/2120205/190024703-e59bf222-1e13-4cd1-b877-a3c8c4a5d5ff.png)

**Comment by xchwarze** [comment]
The installation must be done with these parameters:
`sysupgrade -n -F /tmp/archer-c7-v5-tetra-sysupgrade.bin`

**Comment by nullc0rp** [comment]
That was it, I needed the -n flag on sysupgrade. Thanks for the help!
