### ISSUE TITLE
Cant complete setup | ArcherC7 v2.0

### ISSUE THREAD

**Issue by fitfrost4** [xchwarze/wifi-pineapple-cloner#18]
Currently trying to flash the already prebuild image to an ArcherC7 v2.0. The flash process worked but when the setup asks me to press the wps/reset button the device resets and you cant complete it.

Seems like the contestant project worked that out by swapping the button scripts [(Sweet Pineapple Builder GitLab)](https://gitlab.com/0xSamy/sweet-pineapple-builder/-/issues/7)

> Yes, my repo produces a .bin file exactly as the original repo (if you see my pull request, there is only a small modification to one of the scripts, to replace the `/etc/rc.button/wps` script with `/etc/rc.button/reset` script).
The router can be always (re)flashed with TFTP following the instructions here: https://openwrt.org/toh/tp-link/archer_c7#installation_or_restore_with_tftp

This fix should be included for the Archer series

**Comment by xchwarze** [comment]
If you read the readme you will know that Samy Younsi copied his project from the first version of mine. The bug you mention should be fixed, as hak5 made delete the original repo the thread was lost, but the correct fix is this: https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/tools/fs-patcher.sh#L144

if you still have that problem connect via ssh and run `touch /tmp/button_setup` anyway that fix was validated by the user who originally reported it in this repo.

--- edit
I just downloaded archer-c7-v2-universal-sysupgrade.bin and I see that in the build is the patched file and as I said before the fix was already validated.... sure you installed the correct fw... ?

**Comment by fitfrost4** [comment]
No worries, it can be overseen that Samy Younsi copied your method without credit. 

Yes. I have used the latest prebuild image. Connecting via SSH worked out fine. Maybe we could include this tooltip for future users?

Thanks

**Comment by xchwarze** [comment]
When installing did you follow this step?
`You must install it with the do not save configuration over reflash option checked.`
In sysupgrade it is the -n option.

I understand that this is what actually happened in this case because the fix is applied.
