### ISSUE TITLE
Fritzbox4020 NO WIFI on ifconfig pineap not even starting 

### ISSUE THREAD

**Issue by cpcker** [xchwarze/wifi-pineapple-cloner#24]
Just build an clone for fritzbox4020(contained in the supported devices list) done the setup but wifi isnt working no management AP or Pineap there is no wlan on ifconfig too can i get some help from somebody please
Thanks in advance

**Comment by xchwarze** [comment]
From issue template:

Your device logs. Without this, no help can be given.

**Comment by cpcker** [comment]
how can i retrieve those is there any tool?

**Comment by xchwarze** [comment]
```
### Your device logs. Without this, no help can be given.
<!-- Attach debug log from: Help > Feedback and Support > Download Debug File
 -->
````

**Comment by cpcker** [comment]
Logs are like this seems like im missing a lot of things 
debug log from: Help > Feedback and Support > Download Debug File
>  -->
[debug.log](https://github.com/xchwarze/wifi-pineapple-cloner/files/15197639/debug.log)

>

**Comment by xchwarze** [comment]
I don't see any crash of anything in the logs, which makes me think that the default dependencies of this target is wrongly declared and it lacks some network dependency.

Try installing openwrt 19.07.07 and if everything works with luci usage try to generate a list of installed dependencies with opkg --list-instaled (or something like that, check the opkg parameters) surely installing some of that list in your WPC installation will fix it.

But if openwrt 19.07.07 does not work... the problem is probably that some dependency is broken and that version is not stable on that hardware.

**Comment by cpcker** [comment]
I tried building a new image of 19.07.7 with luci the AP works normally when I try to "make" a new image of wifipineapple it get an error which I got previously too but just removed the package so I´m guessing thats the issue 
"Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for iwinfo:
 * 	libubus20191227
 * opkg_install_cmd: Cannot install package iwinfo.
make[2]: *** [Makefile:158: package_install] Error 255
make[1]: *** [Makefile:118: _call_image] Error 2
make: *** [Makefile:208: image] Error 2"

If you have the time can you assist me over discord or something

**Comment by cpcker** [comment]
Fixed the build added the package manually yet still wifi is nowhere to be found 
"pineap run_scan 10 0
returns: Failed to connect to socket at path: /var/run/pineapd.sock: No such file or directory"
ifconfig prints out: br-lan , eth0 , eth1, lo

**Comment by xchwarze** [comment]
from mi last response:
```
I don't see any crash of anything in the logs, which makes me think that the default dependencies of this target is wrongly declared and it lacks some network dependency.

Try installing openwrt 19.07.07 and if everything works with luci usage try to generate a list of installed dependencies with opkg --list-instaled (or something like that, check the opkg parameters) surely installing some of that list in your WPC installation will fix it.
```

The problem is not in these scripts (WPC) but that there is one more step missing for your particular hardware.

Surely the missing step is that you have to manually install a dependency. To solve it you must do what I put in that previous comment and generate the list of dependencies that has openwrt installed by default and compare them with those you have in the installation of WPC.
Then based on that comparison you install the missing ones referred to network/wifi package.
