### ISSUE TITLE
USB WiFi in Wireless config

### ISSUE THREAD

**Issue by APToni** [xchwarze/wifi-pineapple-cloner#42]
How to add new USB WiFi in Wireless config (Generic RT5370 WIFI adapter or MT7612U WIFI adapter) on GL-AR150?

**Comment by xchwarze** [comment]
Yes they should work, but that hardware is very old and very tight. I recommend the GL-AR750S.

**Comment by xchwarze** [comment]
I didn't say it didn't work. I said I don't recommend that hard if you are going to use it with 5ghz (MT7612U ).

**Comment by xchwarze** [comment]
All this development and tested on a GL-AR150.
But it works much better on a GL-AR750S.
For example the nano and it didn't even work scanning at 5ghz.

**Comment by xchwarze** [comment]
This is my AR150

![image](https://user-images.githubusercontent.com/2120205/211907081-016966cb-d76c-4962-b5b5-71ac4ebcaca0.png)

**Comment by APToni** [comment]
> All this development and tested on a GL-AR150. But it works much better on a GL-AR750S. For example the nano and it didn't even work scanning at 5ghz.

Generic [RT5370 WIFI adapter](https://www.ebay.com/itm/284904442887) or [MT7612U WIFI adapter](https://www.ebay.com/itm/175219205235) you're really going to **need this on hardware that doesn't have two wifi adapters**

**Comment by APToni** [comment]
This is called neither to yourself nor to others. You would already write it will not work, why give hope, and then say that it's all outdated, and solve your problems yourself.

**Comment by xchwarze** [comment]
The issues that are errors I leave open and those that are questions I close them and continue answering in the same thread.

The screenshots are almost all taken on an AR150 so it is even documented that it works.
As the project says everything works the same as on the real hardware and the nano which has the same hard as the ar150 does not scan at 5ghz.

On the other hand, I think that someone who doesn't even know what he is doing shouldn't give an opinion on whether something has to be alpha, beta or productive.

**Comment by xchwarze** [comment]
let's take it one step at a time:
1) The list is made with OpenWRT data, if any is wrong you can correct the listing in openwrt and here sending PR.
2) The recommended hard recommended works all and is tested.
3) As a realistic recommendation it would be best to look for the best hard and that would be the GL-AR750S with a MT7612U.
4) I answered every single question you left in all the threads and yet you continue to disrespect me. So have some respect for someone who maintains something for a bunch of crybabies who do not even know how to choose a router, or what is openwrt.

If you want to use the AR150 + MT7612U you will have no problem but it will not have the best performance.

**Comment by xchwarze** [comment]
1. I can't buy 211 routers to test how each one works to maintain a public project that doesn't even generate money for me.
The list as I said several times is made with the official OpenWRT data, if they have it wrong is beyond my control.
That's why there is a recommended setup that is the one I have and I can test if there is a problem.
Setup that works for many people.

2. You want to have a pineapple nano that scans at 5ghz, but the hardware is at the limit for that use case.
It's a limit of your hard, not the project. Anyway, this project is made so that you can do it but it is not what I would recommend. 

3. If you look in the old threads there are many using the project on the AR150 and I include myself in them.
https://github.com/xchwarze/wifi-pineapple-cloner/issues/16
