### ISSUE TITLE
Wlan0 non working

### ISSUE THREAD

**Issue by MDRafi08642** [xchwarze/wifi-pineapple-cloner#47]
router model: netgear r6120

Wlan0 not working. Recon scan(2.4G) not working

![Screenshot 2023-02-18 130417](https://user-images.githubusercontent.com/81744420/219847271-b8a136d8-423c-44af-aa69-3eb8470de082.png)

!please don't close this issue until it solved...

**Comment by MDRafi08642** [comment]
@xchwarze 

Hey, why you closed this issuse without solving?

**Comment by xchwarze** [comment]
The project gives a recommended setup because it is the one that works easily for everyone (even if they don't know what they are doing).

If another router is used the user has to understand the minimum of openwrt and linux, otherwise he will not really know what to do with the tool.

**Comment by APToni** [comment]
I have the same problem

**Comment by APToni** [comment]
> @xchwarze
> 
> Эй, почему ты закрыл эту проблему, не решив?

Hello, the point is this: you take a WiFi adapter AR9271 or similar, insert it into the usb and install the drivers via ssh, for example opkg install kmod-ath9k-htc, after which it appears in your monitor web interface, and you start working, the author is probably not wants to share in order to avoid responsibility, but thank him very much for his work.

**Comment by xchwarze** [comment]
No, actually the wifi of the routers is included in the required dependencies section injected by OpenWrt. This happens automatically when you choose the target in the openwrt builder.

If it happens that the router's internal boards are not detected in the wifi device list, one of two things can happen:
1. That router is not configured correctly in the mandatory dependencies section in that version of OpenWrt.
2. That version of openwrt has a broken dependency and that is manifested in this way. This is normal with OpenWrt 19 and some internal 5ghz adapters.

Both of these things are beyond the scope of this project.
That's why I added a recommended setup that always works in all cases and for everybody.
