### ISSUE TITLE
Stuck on Secure Setup

### ISSUE THREAD

**Issue by magicmex** [xchwarze/wifi-pineapple-cloner#51]
Hello,
I have built and successfully flashed the Pineapple firmware for the Mikrotik RB915G-2HnD. I can login via ssh and the setup module starts when I go to http://172.16.42.1:1471 in the browser. The problem is that I'm stuck on the Secure Setup screen where I have to press the reset/WPS button to disable WiFi or continue insecurely with WIFI on. Unfortunately nothing happens when I press the reset button on the RouterBoard.
![SecureSetup](https://user-images.githubusercontent.com/4005991/224538339-0f4880a8-9228-4df3-8cea-56eafa22364d.png)

Is there a way to do it via ssh or is there a patch for the setup modul that i can use to complete the setup?

**Comment by xchwarze** [comment]
Hi!
The two causes of this error are:

1) Not doing a clean firmware installation. This would be when we don't check the "do not save configuration over reflash" in the OpenWrt updater or when we use the sysupgrade command without the "-n".

2) In the step of patching of FS the scripts for reset and wps were not copied. These would be [reset](https://pastebin.com/YMn9vzTL) and [wps](https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/files/common/etc/wps), you would have to verify the content of them in your installation folder \etc\rc.button\ to see if they are the correct ones. 
If they are not and it is a handmade build **you would have to rebuild** because there might be more things missing in that build.

these are the only causes for this to happen.
